version: '3.3'
services:
    db:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Passw0rd
        ports:
            - '1433:1433'
        image: mcr.microsoft.com/mssql/server:2019-latest
